// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protos.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Messages {
  public static partial class HelloGrain
  {
    static readonly string __ServiceName = "messages.HelloGrain";

    static readonly grpc::Marshaller<global::Messages.HelloRequest> __Marshaller_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messages.HelloResponse> __Marshaller_HelloResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messages.HelloResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Messages.HelloRequest, global::Messages.HelloResponse> __Method_SayHello = new grpc::Method<global::Messages.HelloRequest, global::Messages.HelloResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_HelloRequest,
        __Marshaller_HelloResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Messages.ProtosReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloGrain</summary>
    public abstract partial class HelloGrainBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Messages.HelloResponse> SayHello(global::Messages.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloGrain</summary>
    public partial class HelloGrainClient : grpc::ClientBase<HelloGrainClient>
    {
      /// <summary>Creates a new client for HelloGrain</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloGrainClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloGrain that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloGrainClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloGrainClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloGrainClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Messages.HelloResponse SayHello(global::Messages.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messages.HelloResponse SayHello(global::Messages.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.HelloResponse> SayHelloAsync(global::Messages.HelloRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messages.HelloResponse> SayHelloAsync(global::Messages.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloGrainClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloGrainClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloGrainBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

  }
}
#endregion
